language: c

sudo: required
dist: trusty

notifications:
  email: false

before_script:
# travis has changed to 64-bit and we require 32-bit compatibility libraries
  - sudo apt-get update
  - "sudo apt-get install -qq python3-pyqt5 pyqt5-dev pyqt5-dev-tools libreadline6 libreadline6-dev libgtk2.0-dev libgtk-3-dev || true"
  - "sudo apt-get install -qq gcc-arm-none-eabi || true"

script:
  - cd release/asboot && make 91 && make 92 && make 11 && make 12 && make 21 && make 22
#  - cd ../../release/ascore && make 91 && make 92 && make 01 && make 02 && make 11 && make 12 && make 31 && make 32
  - cd ../../release/aslua && make 91 && make 94 && make 81 && make 82

env:
  - EMAIL='parai@foxmail.com'
 
