language: c

notifications:
  email: false

before_script:
# travis has changed to 64-bit and we require 32-bit compatibility libraries
  - sudo apt-get update
  - "sudo apt-get -qq install clang gcc-multilib libc6:i386 libgcc1:i386 gcc-4.6-base:i386 libstdc++5:i386 libstdc++6:i386 libsdl-dev || true"
  - "[ $AS_TOOL_CHAIN = 'sourcery-arm' ] && curl -s https://sourcery.mentor.com/public/gnu_toolchain/arm-none-eabi/arm-2014.05-28-arm-none-eabi-i686-pc-linux-gnu.tar.bz2 | sudo tar xjf - -C / && /opt/arm-2014.05/bin/arm-none-eabi-gcc --version || true"
  - "[ $AS_TOOL_CHAIN = 'sourcery-mips' ] && curl -s https://sourcery.mentor.com/public/gnu_toolchain/mips-sde-elf/mips-2012.09-98-mips-sde-elf-i686-pc-linux-gnu.tar.bz2 | sudo tar xjf - -C / && /opt/mips-2012.09/bin/mips-sde-elf-gcc --version || true"
  - "[ $AS_TOOL_CHAIN = 'sourcery-ppc' ] && curl -s https://sourcery.mentor.com/public/gnu_toolchain/powerpc-eabi/freescale-2011.03-39-powerpc-eabi-i686-pc-linux-gnu.tar.bz2 | sudo tar xjf - -C / && /opt/freescale-2011.03/bin/powerpc-eabi-gcc --version || true"
  - "[ $AS_TOOL_CHAIN = 'atmel-avr32' ] && curl -s http://www.atmel.com/images/avr32-gnu-toolchain-3.4.1.348-linux.any.x86.tar.gz | sudo tar xzf - -C / && /opt/avr32-gnu-toolchain-linux_x86/bin/avr32-gcc --version || true"

script:
  - cd release/ascore && make 91 && make 92
  - cd release/asboot && make 91 && make 92

env:
  - AS_TOOL_CHAIN='sourcery-arm'
 