# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Automotive Software
email: parai@foxmail.com
description: > # this means to ignore newlines until "baseurl:"
  This github repository https://github.com/parai/as is dedicated for 
  a collection of open source software for automotive, only some of them are
  written by me directly, most of job is to do the integration and create
  a configuraton tool and a validation tool, such as the easySAR configuration 
  studio and the aslua script, also, this repository is for study purpose by me.
baseurl: "/"
#url: "http://parai.github.io/as" # the base hostname & protocol for your site
github_username:  parai

# Build settings
markdown: kramdown
